name: tidal
description: A Dart library for connecting to and interacting with the Tidal Developer Portal APIs.
version: 0.3.0
repository: https://github.com/filippomenchini/tidal

environment:
  sdk: ^3.1.3

dependencies:
  equatable: ^2.0.5
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
